spring:
  application:
    name: client-service-2 #name should be equal to bootstrap's one
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8800/eureka/,http://localhost:8801/eureka/,http://localhost:8802/eureka/    
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${spring.profiles.active}
management:
  endpoints:
    web:
      exposure:
        include: "*"    
---
spring:
  profiles: peer1
eureka:
  instance:
    metadata-map:
      zone: zone1
server:
  port: ${port:8821}
---
spring:
  profiles: peer2
eureka:
  instance:
    metadata-map:
      zone: zone2
server:
  port: ${port:8822}
---
spring:
  profiles: peer3
eureka:
  instance:
    metadata-map:
      zone: zone3
server:
  port: ${port:8823}