# client-service implements discovery-first-bootstrap
# it registers itself to eureka discovery and find configuration server among eureka instances
spring:
  application:
    name: client-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
