spring:
  application:
    name: client-service #name should be equal to bootstrap's one
  port: 0 #random port
  config:
    import: optional:configserver:http://localhost:9000
my-config.name: default
eureka:
  instance:
    prefer-ip-address: true # if you don't have own your DNS servers, perfer-ip-address is useful.
    instance-id: ${spring.application.name}  
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
