server:
  port: 8762 #포트번호 지정

spring:
  application:
    name: discovery-server # 서비스 ID

eureka:
  client:
    register-with-eureka: false # default : true
    fetch-registry: false # default : true
